apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: user-service
spec:
  type: ClusterIP
  ports:
  - port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: user
  type: LoadBalancer
status:
  loadBalancer: {}
