apply:
	kubectl delete -f ./env \
	kubectl delete -f ./mysql \
	kubectl delete -f ./phpmyadmin \
	kubectl delete -f ./user \
	kubectl delete -f ./graphql \
	kubectl apply -f ./env \
	kubectl apply -f ./mysql \
	kubectl apply -f ./phpmyadmin \
	kubectl apply -f ./user \
	kubectl apply -f ./graphql