apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: phpmyadmin-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: phpmyadmin
    spec:
      containers:
      - image: phpmyadmin/phpmyadmin
        name: phpmyadmin
        env:
        - name: PMA_ARBITRARY
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: PMA_ARBITRARY
        - name: PMA_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: MYSQL_SERVICE_NAME
        - name: PMA_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: MYSQL_USER
        - name: PMA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        resources: {}
status: {}
