apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: phpmyadmin-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: phpmyadmin
    spec:
      containers:
      - image: phpmyadmin/phpmyadmin
        name: phpmyadmin
        env:
        - name: PMA_ARBITRARY
          value: "1"
        - name: PMA_HOST
          value: mysql-service
        - name: PMA_USER
          value: root
        - name: PMA_PASSWORD
          value: password
        resources: {}
status: {}
