apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: phpmyadmin-service
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 80
  selector:
    app: phpmyadmin
  type: LoadBalancer
status:
  loadBalancer: {}
