apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  name: local-pv-1
spec:
  storageClassName: sc-db
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/engineer/workspace/kube_mysql"