apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: dev
spec:
  storageClassName: sc-db # この設定でPVとバインドされる
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi