apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: mysql-pv-claim
spec:
  storageClassName: sc-db
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi