apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: go-pf
  name: graphql-service
spec:

  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: graphql-deploy
  type: LoadBalancer
status:
  loadBalancer: {}
