apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: graphql-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: graphql
status:
  loadBalancer: {}
