apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: go-pf
  name: go-pf
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: go-pf
status:
  loadBalancer: {}
