name: User service image build and push
on:
  push:
    branches:
    - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/user
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build
      run: |
        docker build -t 002146139975.dkr.ecr.ap-northeast-1.amazonaws.com/go-pf/user:$GITHUB_SHA -f build/Dockerfile .
    - name: Push
      run: |
        docker push 002146139975.dkr.ecr.ap-northeast-1.amazonaws.com/go-pf/user:$GITHUB_SHA